module K = Check
module PP = Pp
module SC = Spec_count
let ck_ctx g = K.make g Budget.unlimited
let ck_budget g n =
  let remaining = ref n in
  K.make g (Budget.of_poll (fun () -> if !remaining <= 0 then true else (decr remaining; false)))
let ck_error e = "error:" ^ Error.to_string e
let ck_unit r = Result.fold ~ok:(fun () -> "ok") ~error:ck_error r
let ck_value c r = Result.fold ~ok:(fun t -> "ok:" ^ Pp.term (Check.names_of c) t) ~error:ck_error (Result.bind r (Eval.quote c.Check.globals c.Check.size))
let ck_infer c q t = ck_value c (K.infer c q t)
let ck_check c q t ty = ck_unit (Result.bind (Eval.eval c.Check.globals c.Check.env ty) (K.check c q t))
let ck_univ c t = Result.fold ~ok:(fun l -> "ok:" ^ L.to_string l) ~error:ck_error (K.infer_univ c t)
let ck_bool = string_of_bool
let ck_range (lo, hi) = Q.to_string lo ^ ":" ^ Q.to_string hi
let ck_usage u level = String.concat "," [ck_range (Q.get level u); ck_bool (Q.exactly_once level u); ck_bool (Q.at_most_once level u); ck_bool (Q.used level u)]
let ck_decls g ds = Result.fold ~ok:(fun xs -> "ok:" ^ String.concat "" (List.map (fun (n, _) -> n ^ ";") xs)) ~error:ck_error (K.check_decls g ds)
let ck_global r = Result.fold ~ok:(fun _ -> "ok") ~error:ck_error r
let ck_family g d = ck_global (K.declare_family g d)
let ck_family_twice g d = ck_global (Result.bind (K.declare_family g d) (fun next -> K.declare_family next d))
let ck_install g d group name cs = Result.bind (K.declare_family g d) (fun next -> K.define_ctors next ~group ~name cs)
let ck_ctors g d group name cs = ck_global (ck_install g d group name cs)
let ck_family_infer g d group name cs t = Result.fold ~error:ck_error ~ok:(fun next -> ck_infer (ck_ctx next) Q.Many t) (ck_install g d group name cs)
let ck_family_check g d group name cs t ty = Result.fold ~error:ck_error ~ok:(fun next -> ck_check (ck_ctx next) Q.Many t ty) (ck_install g d group name cs)
let ck_install_twice g d group name cs = ck_global (Result.bind (ck_install g d group name cs) (fun next -> K.define_ctors next ~group ~name cs))
let ck_provisional g d t = Result.fold ~error:ck_error ~ok:(fun next -> ck_infer (ck_ctx next) Q.Many t) (K.declare_family g d)
