#!/usr/bin/env python3
"""Build bin/sole-comb.bend with the pinned Bend 2 binary and cache by transitive source hashes.

Usage: python3 -P dev/build.py [--backend js|native|all] [--check]

Copied from attest/dev/build.py and assay/dev/build.py (M0 plan S0-3, 8.3):
- Before the first compile it runs dev/pin-check.py --only bend. That refuses a
  Bend checkout whose HEAD is not the pin, a checkout with modified tracked
  sources, and a binary whose sha256 is not the pin.
- Every bend run sets BEND_NO_TELEMETRY=1 and BEND_LIB=_build/bend-cache, runs
  from the sole-comb root, and is bounded by build_deadline_s.
- The output is cached by transitive source hashes, compiler identity and
  options. The output sha256 is checked before reuse. The hashes cover every
  header import (indented or not) and every foreign `import "<path>.c|js"` file
  that Bend reads. Content-addressed 0x<hash>/ imports are skipped.
- js writes _build/sole-comb.js and the endpoint launchers _build/endpoint/bun
  and _build/endpoint/node-worker. native writes _build/native/sole-comb.exe
  and _build/endpoint/native (INFO only: the full native build is not
  validated, and the native path without the attest CC wrapper is UNVERIFIED).
- ./sole-comb is written only when dev/toolchain.json names an endpoint, and
  only for one of endpoint_candidates (bun, node-worker). native is INFO only
  and is never activated. At Stage 0 the endpoint is null (S0-5 picks it).

Exit codes: 0 built or cached, 1 failure, 3 UNMET (the build passed build_deadline_s).
"""
import argparse
from functools import reduce
import hashlib
import json
import os
from pathlib import Path
import re
import resource
import shutil
import subprocess
import sys
import time

ROOT = Path(__file__).resolve().parent.parent
TOOLCHAIN = Path(os.environ.get("SOLE_COMB_TOOLCHAIN", ROOT / "dev/toolchain.json"))
ENTRY = "bin/sole-comb.bend"
OUTPUTS = {"js": "_build/sole-comb.js", "native": "_build/native/sole-comb.exe"}
IMPORT = re.compile(r"^[^\S\n]*import[^\S\n]+(\S+\.bend)(?:[^\S\n]+as[^\S\n]+\w+)?[^\S\n]*(?:(?://|#)[^\n]*)?$", re.M)
FOREIGN = re.compile(r'\bimport\s*"([^"\n]*\.(?:c|js))"')
CONTENT_ADDRESSED = re.compile(r"^0x[0-9a-f]+/")
UNMET = 3


class Unmet(Exception):
    pass


def digest(data):
    return hashlib.sha256(data).hexdigest()


def inside(path):
    if ROOT not in path.parents:
        raise ValueError(f"source import escapes the repository: {path}")
    return path


def dependencies(source, seen=frozenset()):
    """Bend .bend imports recursively, plus foreign .c/.js files as leaves."""
    source = source.resolve()
    if source in seen:
        return seen
    text = inside(source).read_text()
    foreign = frozenset(inside((source.parent / name).resolve()) for name in FOREIGN.findall(text))
    return reduce(lambda acc, imported: dependencies(source.parent / imported, acc),
                  [name for name in IMPORT.findall(text) if not CONTENT_ADDRESSED.match(name)],
                  seen | {source} | foreign)


def source_hashes():
    return {str(path.relative_to(ROOT)): digest(path.read_bytes())
            for path in sorted(dependencies(ROOT / ENTRY))}


def children_cpu_s():
    usage = resource.getrusage(resource.RUSAGE_CHILDREN)
    return usage.ru_utime + usage.ru_stime


def compiler(pins):
    refusal = subprocess.run([sys.executable, "-P", str(ROOT / "dev/pin-check.py"),
                              "--toolchain", str(TOOLCHAIN), "--only", "bend"])
    if refusal.returncode:
        raise ValueError("the pinned Bend checkout or binary does not match dev/toolchain.json")
    return Path(pins["bend"]["binary"]), pins["bend"]["revision"], pins["bend"]["binary_sha256"]


def write_executable(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.is_file() or path.read_text() != text:
        path.write_text(text)
    path.chmod(0o755)


def node_worker_script(pins):
    return ("const { Worker } = require('node:worker_threads'); "
            "const worker = new Worker(require('node:path').resolve(process.argv[1]), { argv: process.argv.slice(2), execArgv: [], "
            f"resourceLimits: {{ stackSizeMb: {pins['stack_kib'] / 1024} }} }}); "
            "worker.on('error', error => { process.stderr.write(String(error.stack || error) + '\\n'); process.exitCode = 1; }); "
            "worker.on('exit', code => { process.exitCode = code || process.exitCode || 0; });")


def endpoint_launchers(pins, backend, output):
    header = (f"#!/bin/sh\n# sole-comb endpoint, generated by dev/build.py\n# output sha256:{digest(output.read_bytes())}\n"
              "BEND_NO_TELEMETRY=1\nexport BEND_NO_TELEMETRY\n")
    target = '"$(dirname -- "$0")/' + os.path.relpath(output, ROOT / "_build/endpoint") + '"'
    tools = pins["tools"]
    js = {"bun": f'exec "{tools["bun"]["path"]}" {target} "$@"\n',
          "node-worker": f'exec "{tools["node"]["path"]}" -e "{node_worker_script(pins)}" {target} "$@"\n'}
    scripts = js if backend == "js" else {"native": f'exec {target} "$@"\n'}
    [write_executable(ROOT / "_build/endpoint" / name, header + body) for name, body in scripts.items()]
    return sorted(scripts)


def activate(pins):
    launcher = ROOT / "sole-comb"
    endpoint = pins["endpoint"]
    chosen = ROOT / "_build/endpoint" / str(endpoint)
    if endpoint is None:
        launcher.unlink(missing_ok=True)
        print("LAUNCHER ./sole-comb not written: endpoint is null in dev/toolchain.json (S0-5 picks it)", flush=True)
    elif endpoint not in pins["endpoint_candidates"]:
        raise ValueError(f"endpoint {endpoint} is not one of endpoint_candidates {pins['endpoint_candidates']}")
    elif not chosen.is_file():
        raise ValueError(f"endpoint {endpoint} has no launcher; build its backend first")
    else:
        write_executable(launcher, '#!/bin/sh\nexec "$(dirname -- "$0")/_build/endpoint/' + endpoint + '" "$@"\n')
        print(f"LAUNCHER ./sole-comb -> _build/endpoint/{endpoint}", flush=True)


def fingerprint(pins, backend, sources, compiler_hash, revision):
    options = {"backend": backend,
               "cc": os.environ.get("SOLE_COMB_CC", os.environ.get("CC", "clang")) if backend == "native" else None}
    return digest(json.dumps({"sources": sources, "revision": revision, "compiler": compiler_hash,
                              "builder": digest(Path(__file__).read_bytes()), "options": options},
                             sort_keys=True).encode())


def cached(output, stamp, print_key):
    if not (output.is_file() and stamp.is_file()):
        return False
    previous = json.loads(stamp.read_text())
    return previous.get("fingerprint") == print_key and previous.get("output_sha256") == digest(output.read_bytes())


def compile_once(arguments, log, deadline, extra_env):
    env = {**os.environ, **extra_env, "BEND_NO_TELEMETRY": "1", "BEND_LIB": str(ROOT / "_build/bend-cache")}
    cpu0, wall0 = children_cpu_s(), time.perf_counter()
    try:
        result = subprocess.run(arguments, cwd=ROOT, capture_output=True, env=env, timeout=deadline)
    except subprocess.TimeoutExpired as expired:
        log.write_bytes((expired.stdout or b"") + (expired.stderr or b""))
        raise Unmet(f"bend passed build_deadline_s={deadline}; log={log.relative_to(ROOT)}")
    log.write_bytes(result.stdout + result.stderr)
    return result, time.perf_counter() - wall0, children_cpu_s() - cpu0


def build(pins, backend, check_only, command):
    binary, revision, compiler_hash = command
    output = ROOT / OUTPUTS[backend]
    stamp = output.with_name(output.name + ".json")
    sources = source_hashes()
    print_key = fingerprint(pins, backend, sources, compiler_hash, revision)
    if not check_only and cached(output, stamp, print_key):
        print(f"BUILD sole-comb {backend} cached", flush=True)
        return endpoint_launchers(pins, backend, output)
    logs = ROOT / ".gatework/build"
    logs.mkdir(parents=True, exist_ok=True)
    output.parent.mkdir(parents=True, exist_ok=True)
    (ROOT / "_build/bend-cache").mkdir(parents=True, exist_ok=True)
    log = logs / f"sole-comb-{backend}{'-check' if check_only else ''}.log"
    temporary = output.with_name(output.stem + ".building" + output.suffix)
    arguments = ([str(binary), ENTRY, "--check-only"] if check_only
                 else [str(binary), ENTRY, "-o", str(temporary.relative_to(ROOT))])
    native_env = ({"CC": os.environ.get("SOLE_COMB_CC", os.environ.get("CC", shutil.which("clang") or "clang"))}
                  if backend == "native" else {})
    print(f"BUILD sole-comb {backend} {'check' if check_only else 'compile'}: {' '.join(arguments)}", flush=True)
    result, wall_s, cpu_s = compile_once(arguments, log, pins["build_deadline_s"], native_env)
    if result.returncode:
        sys.stderr.buffer.write(result.stdout + result.stderr)
        raise ValueError(f"sole-comb {backend} exit={result.returncode}; log={log.relative_to(ROOT)}")
    if source_hashes() != sources:
        temporary.unlink(missing_ok=True)
        raise ValueError("sources changed during compilation; rerun the build")
    timing = f"wall_s={wall_s:.3f} child_cpu_s={cpu_s:.3f}"
    if check_only:
        print(f"BUILD sole-comb {backend} check OK {timing}", flush=True)
        return []
    temporary.replace(output)
    stamp.write_text(json.dumps({"fingerprint": print_key, "output_sha256": digest(output.read_bytes()),
                                 "revision": revision, "compiler_sha256": compiler_hash,
                                 "sources": sources}, indent=2) + "\n")
    print(f"BUILD sole-comb {backend} OK {timing} output={output.relative_to(ROOT)} "
          f"sha256={digest(output.read_bytes())}", flush=True)
    return endpoint_launchers(pins, backend, output)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--backend", choices=("js", "native", "all"), default="js")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    pins = json.loads(TOOLCHAIN.read_text())
    command = compiler(pins)
    backends = ("js", "native") if args.backend == "all" else (args.backend,)
    endpoints = [name for backend in backends for name in build(pins, backend, args.check, command)]
    print(f"ENDPOINTS {' '.join(endpoints)}", flush=True) if endpoints else None
    (activate(pins) if not args.check else None)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Unmet as unmet:
        print(f"BUILD UNMET: {unmet}", file=sys.stderr)
        sys.exit(UNMET)
    except (OSError, ValueError, KeyError, TypeError, subprocess.SubprocessError) as error:
        print(f"BUILD FAIL: {error}", file=sys.stderr)
        sys.exit(1)
